### ISSUE TITLE
Only works with Node, not in the browser

### ISSUE THREAD

**Issue by OscarGodson** [polotek/ctor#2]
I'll probably be able to send a PR, but filing a ticket for now. What I like about this is for one it's familiar (obviously), but it's super tiny. I was a little sad to see it requires Node, so it'd be cool to have this work on the browser and be able to simply plop it in and code.

**Comment by polotek** [comment]
The reason I didn't bother making this browser friendly is that when you're doing non-trivial things in the browser, you usually end up with some form of library or framework. That framework usually has some opinionated form of inheritance in it. I don't know if it pays to mix patterns by having this and some other form in the same code.

**Comment by OscarGodson** [comment]
In regards to browser + ctor, I see this as a piece to add to your custom framework or as a starting point to your app. Think yam.js for example. Back when it was decided to go in-house developed framework, we could have dropped this into yam.js and built on top of this. That's actually why I'm interested in this project. I was playing around with trying to do the same thing. I'd also like to add in a separate module a data / ORM / collections piece you could add to extend Ctor. So you could do something like:

``` js
var Person = Ctor.extend({
  constructor: function Person(name, nickname) {
    this.name = name;
    this.nickname = nickname;
  }
});

var p = Person.create('Marco', 'polotek');
var p = Person.create('Oscar', 'oscargodson');
p.save();

// Later on you could do...
Person.find({ name: 'Oscar' }); // => { name: 'Oscar', nickname: 'oscargodson' }
```

Anyway, I'm trying to get a Jake build task, but having issues with browserify. Not sure if it's just me or browserify so I created a ticket: https://github.com/substack/node-browserify/issues/369

The build task would, for now, just copy index.js to `/ctor/node/index.js` and browserify `/ctor/browser/ctor.js` and `/ctor/browser/ctor.min.js`. This way you could use this in any environment. If you're fine with it I could also move `index.js` to `/src/index.js`

**Comment by polotek** [comment]
The only thing that's really threatening decent browser support is a few
things from es5 that aren't available in IE < 9. `Object.create`  and some
stuff in @izaacs's `inherits` module. Those will have to be shimmed. There
is an `inherits-old` in that package that will work well enough in old IE.

I would like things to keep working as usual in node. You can compile a
browser version in `browser/ctor.js`. But I'd like to leave the node
version of `index.js` at the root of the package. No need to move it.

On Mon, Apr 1, 2013 at 12:13 AM, Oscar Godson notifications@github.comwrote:

> In regards to browser + ctor, I see this as a piece to add to your custom
> framework or as a starting point to your app. Think yam.js for example.
> Back when it was decided to go in-house developed framework, we could have
> dropped this into yam.js and built on top of this. That's actually why I'm
> interested in this project. I was playing around with trying to do the same
> thing. I'd also like to add in a separate module a data / ORM / collections
> piece you could add to extend Ctor. So you could do something like:
> 
> var Person = Ctor.extend({
>   constructor: function Person(name, nickname) {
>     this.name = name;
>     this.nickname = nickname;
>   }});
> var p = Person.create('Marco', 'polotek');var p = Person.create('Oscar', 'oscargodson');p.save();
> // Later on you could do...Person.find({ name: 'Oscar' }); // => { name: 'Oscar', nickname: 'oscargodson' }
> 
> Anyway, I'm trying to get a Jake build task, but having issues with
> browserify. Not sure if it's just me or browserify so I created a ticket:
> substack/node-browserify#369https://github.com/substack/node-browserify/issues/369
> 
> The build task would, for now, just copy index.js to /ctor/node/index.jsand browserify
> /ctor/browser/ctor.js and /ctor/browser/ctor.min.js. This way you could
> use this in any environment. If you're fine with it I could also move
> index.js to /src/index.js
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/polotek/ctor/issues/2#issuecomment-15706342
> .

## 

Marco Rogers
marco.rogers@gmail.com | https://twitter.com/polotek

Life is ten percent what happens to you and ninety percent how you respond
to it.
- Lou Holtz
